fruits = []
f = input("Enter a fruit: ")
print("You entered:",f)
fruits.append(f)
f = input("Enter a fruit: ")
print("You entered:",f)
fruits.append(f)
f = input("Enter a fruit: ")
print("You entered:",f)
fruits.append(f)
f = input("Enter a fruit: ")
print("You entered:",f)
fruits.append(f)
f = input("Enter a fruit: ")
print("You entered:",f)
fruits.append(f)
f = input("Enter a fruit: ")
print("You entered:",f)
fruits.append(f)
f = input("Enter a fruit: ")
print("You entered:",f)
fruits.append(f)
print("List of fruits:",fruits)