MarksStudents = []
m = input('Enter marks of student 1: ')
m = int(m)
print("Marks entered:",m,"of",type(m))
MarksStudents.append(m)
m = input('Enter marks of student 2: ')
m = int(m)                           
print("Marks entered:",m,"of",type(m))
MarksStudents.append(m)              
m = input('Enter marks of student 3: ')
m = int(m)                           
print("Marks entered:",m,"of",type(m))
MarksStudents.append(m)              
m = input('Enter marks of student 4: ')
m = int(m)                           
print("Marks entered:",m,"of",type(m))
MarksStudents.append(m)              
m = input('Enter marks of student 5: ')
m = int(m)
print("Marks entered:",m,"of",type(m))
MarksStudents.append(m)
m = input('Enter marks of student 6: ')
m = int(m)
print("Marks entered:",m,"of",type(m))
MarksStudents.append(m)
MarksStudents.sort()
print("Sorted marks of students:",MarksStudents)