s = set()
a = input("Enter number 1: ")
print("You entered:",a)
s.add(int(a))
a = input("Enter number 2: ")
print("You entered:",a)
s.add(int(a))
a = input("Enter number 3: ")
print("You entered:",a)
s.add(int(a))
a = input("Enter number 4: ")
print("You entered:",a)
s.add(int(a))
a = input("Enter number 5: ")
print("You entered:",a)
s.add(int(a))
a = input("Enter number 6: ")
print("You entered:",a)
s.add(int(a))
a = input("Enter number 7: ")
print("You entered:",a)
s.add(int(a))
a = input("Enter number 8: ")
print("You entered:",a)
s.add(int(a))
print("\nAll the unique values entered are:",s)